/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/drops/{dropId}/wish': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: operations['register']
    post?: never
    delete: operations['cancel']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/uploads/images/presigned-url': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['issuePresignedUrl']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/seller/orders/{orderId}/shipment': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['registerShipment']
    delete?: never
    options?: never
    head?: never
    patch: operations['updateShipment']
    trace?: never
  }
  '/api/v1/seller/orders/{orderId}/prepare-shipment': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['prepareShipment']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/seller/drops': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['listDrops']
    put?: never
    post: operations['createDraft']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/seller/drops/{dropId}/publish': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['publish']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/seller/drops/{dropId}/cancel': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['cancel_1']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/orders': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['findMyOrders']
    put?: never
    post: operations['create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/orders/{orderId}/payments': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['pay']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/orders/{orderId}/cancel': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['cancel_2']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/email-verification': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * 이메일 인증 코드 요청
     * @description 가입 여부와 관계없이 같은 응답이며, 메일 발송 완료를 기다리지 않는다. 발송 제한은 MEMBER_AUTH.md 1.2 참고
     */
    post: operations['requestCode']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/email-verification/confirm': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * 이메일 인증 코드 확인
     * @description 성공하면 15분간 유효한 가입 토큰을 email_signup_token HttpOnly 쿠키로 발급한다. 코드 형식 오류는 시도 횟수에 포함하지 않는다
     */
    post: operations['confirmCode']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/seller/drops/{dropId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['findDrop']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch: operations['updateDraft']
    trace?: never
  }
  '/api/v1/users/me/wishes': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['listMyWishes']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/seller/orders': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['listOrders']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/seller/orders/{orderId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['findOrder']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/seller/drops/{dropId}/wish-count': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['findWishCount']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/seller/drops/{dropId}/stocks': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['findStocks']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/seller/dashboard/upcoming-drops': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['findUpcomingDrops']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/seller/dashboard/summary': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['findSummary']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/seller/dashboard/drops': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['findDropStats']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/orders/{orderId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['findMyOrder']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/drops': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['listDrops_1']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/drops/{dropId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getDrop']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/drops/{dropId}/stocks': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getStocks']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/categories': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['listCategories']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    ApiResponseWishResponse: {
      success?: boolean
      data?: components['schemas']['WishResponse']
      message?: string
    }
    WishResponse: {
      /** Format: int64 */
      dropId?: number
      wished?: boolean
      /** Format: date-time */
      wishedAt?: string
      notice?: string
    }
    ImageUploadUrlRequest: {
      fileName: string
      contentType: string
      /** Format: int64 */
      fileSize: number
    }
    ApiResponseImageUploadUrlResponse: {
      success?: boolean
      data?: components['schemas']['ImageUploadUrlResponse']
      message?: string
    }
    ImageUploadUrlResponse: {
      /** Format: uuid */
      imageId?: string
      uploadUrl?: string
      imageUrl?: string
      /** Format: date-time */
      expiresAt?: string
    }
    ShipmentRegisterRequest: {
      carrier: string
      trackingNumber: string
    }
    ApiResponseOrderStatusResponse: {
      success?: boolean
      data?: components['schemas']['OrderStatusResponse']
      message?: string
    }
    OrderStatusResponse: {
      /** Format: uuid */
      orderId?: string
      status?: string
    }
    DropDraftRequest: {
      name?: string
      description?: string
      images?: components['schemas']['DropImageRequest'][]
      /** Format: int64 */
      categoryId?: number
      /** Format: date-time */
      saleStartsAt?: string
      /** Format: date-time */
      saleEndsAt?: string
      shipping?: components['schemas']['ShippingRequest']
      optionGroups?: components['schemas']['OptionGroupRequest'][]
      options?: components['schemas']['OptionRequest'][]
    }
    DropImageRequest: {
      /** Format: uuid */
      imageId: string
      imageUrl: string
    }
    OptionGroupRequest: {
      key: string
      name: string
      /** Format: int32 */
      sortOrder?: number
      values?: components['schemas']['OptionValueRequest'][]
    }
    OptionRequest: {
      selections?: components['schemas']['SelectionRequest'][]
      /** Format: int64 */
      unitPrice: number
      /** Format: int32 */
      totalQuantity: number
      active?: boolean
      /** Format: int32 */
      sortOrder?: number
    }
    OptionValueRequest: {
      key: string
      value: string
      /** Format: int32 */
      sortOrder?: number
    }
    SelectionRequest: {
      groupKey: string
      valueKey: string
    }
    ShippingRequest: {
      /** Format: int64 */
      shippingFee?: number
      shippingNotice?: string
    }
    ApiResponseDropDraftResponse: {
      success?: boolean
      data?: components['schemas']['DropDraftResponse']
      message?: string
    }
    DropDraftResponse: {
      /** Format: int64 */
      dropId?: number
      /** @enum {string} */
      status?: 'DRAFT' | 'WISH' | 'GRAB' | 'ENDED' | 'CANCELED'
      /** Format: date-time */
      createdAt?: string
    }
    ApiResponseDropPublishResponse: {
      success?: boolean
      data?: components['schemas']['DropPublishResponse']
      message?: string
    }
    DropPublishResponse: {
      /** Format: int64 */
      dropId?: number
      /** @enum {string} */
      status?: 'DRAFT' | 'WISH' | 'GRAB' | 'ENDED' | 'CANCELED'
      /** Format: date-time */
      publishedAt?: string
    }
    DropCancelRequest: {
      reason: string
    }
    ApiResponseDropCancelResponse: {
      success?: boolean
      data?: components['schemas']['DropCancelResponse']
      message?: string
    }
    DropCancelResponse: {
      /** Format: int64 */
      dropId?: number
      /** @enum {string} */
      status?: 'DRAFT' | 'WISH' | 'GRAB' | 'ENDED' | 'CANCELED'
      /** Format: date-time */
      canceledAt?: string
    }
    Item: {
      /** Format: int64 */
      optionId: number
      /** Format: int32 */
      quantity: number
    }
    OrderCreateRequest: {
      /** Format: int64 */
      dropId: number
      items: components['schemas']['Item'][]
      shippingAddress: components['schemas']['ShippingAddress']
    }
    ShippingAddress: {
      recipient: string
      phone: string
      postalCode: string
      address1: string
      address2?: string
      deliveryMemo?: string
    }
    ApiResponseOrderCreateResponse: {
      success?: boolean
      data?: components['schemas']['OrderCreateResponse']
      message?: string
    }
    OrderCreateResponse: {
      /** Format: uuid */
      orderId?: string
      orderNumber?: string
      /** @enum {string} */
      status?:
        | 'PAYMENT_PENDING'
        | 'PAID'
        | 'PREPARING'
        | 'SHIPPED'
        | 'DELIVERED'
        | 'EXPIRED'
        | 'CANCELED'
      items?: components['schemas']['Item'][]
      /** Format: int64 */
      itemsAmount?: number
      /** Format: int64 */
      shippingAmount?: number
      /** Format: int64 */
      totalAmount?: number
      /** Format: date-time */
      paymentExpiresAt?: string
    }
    PaymentRequest: {
      paymentKey: string
      /** Format: int64 */
      amount: number
    }
    ApiResponsePaymentResponse: {
      success?: boolean
      data?: components['schemas']['PaymentResponse']
      message?: string
    }
    Failure: {
      code?: string
      message?: string
    }
    PaymentResponse: {
      /** Format: uuid */
      paymentId?: string
      /** Format: uuid */
      orderId?: string
      orderNumber?: string
      /** Format: int64 */
      amount?: number
      /** @enum {string} */
      status?: 'PENDING' | 'SUCCEEDED' | 'FAILED' | 'UNKNOWN' | 'CANCELED'
      /** @enum {string} */
      reconciliationStatus?: 'NONE' | 'REQUIRED' | 'RESOLVED'
      /** Format: date-time */
      paidAt?: string
      failure?: components['schemas']['Failure']
    }
    OrderCancelRequest: {
      reason: string
    }
    ApiResponseOrderCancelResponse: {
      success?: boolean
      data?: components['schemas']['OrderCancelResponse']
      message?: string
    }
    OrderCancelResponse: {
      /** Format: uuid */
      orderId?: string
      /** @enum {string} */
      status?:
        | 'PAYMENT_PENDING'
        | 'PAID'
        | 'PREPARING'
        | 'SHIPPED'
        | 'DELIVERED'
        | 'EXPIRED'
        | 'CANCELED'
      /** @enum {string} */
      refundStatus?: 'NONE' | 'SUCCEEDED' | 'UNKNOWN'
      /** Format: date-time */
      canceledAt?: string
    }
    EmailVerificationRequest: {
      email: string
    }
    EmailVerificationConfirmRequest: {
      email: string
      code: string
    }
    ApiResponseShipmentUpdateResponse: {
      success?: boolean
      data?: components['schemas']['ShipmentUpdateResponse']
      message?: string
    }
    ShipmentUpdateResponse: {
      /** Format: uuid */
      orderId?: string
      status?: string
      carrier?: string
      trackingNumber?: string
    }
    ApiResponsePageResponseWishListResponse: {
      success?: boolean
      data?: components['schemas']['PageResponseWishListResponse']
      message?: string
    }
    PageResponseWishListResponse: {
      content?: components['schemas']['WishListResponse'][]
      /** Format: int32 */
      page?: number
      /** Format: int32 */
      size?: number
      /** Format: int64 */
      totalElements?: number
      /** Format: int32 */
      totalPages?: number
      hasNext?: boolean
    }
    WishListResponse: {
      /** Format: int64 */
      dropId?: number
      name?: string
      thumbnailUrl?: string
      /** Format: int64 */
      minPrice?: number
      /** @enum {string} */
      status?: 'DRAFT' | 'WISH' | 'GRAB' | 'ENDED' | 'CANCELED'
      /** Format: date-time */
      wishedAt?: string
    }
    ApiResponsePageResponseSellerOrderListResponse: {
      success?: boolean
      data?: components['schemas']['PageResponseSellerOrderListResponse']
      message?: string
    }
    PageResponseSellerOrderListResponse: {
      content?: components['schemas']['SellerOrderListResponse'][]
      /** Format: int32 */
      page?: number
      /** Format: int32 */
      size?: number
      /** Format: int64 */
      totalElements?: number
      /** Format: int32 */
      totalPages?: number
      hasNext?: boolean
    }
    SellerOrderListResponse: {
      /** Format: uuid */
      orderId?: string
      orderNumber?: string
      /** Format: int64 */
      dropId?: number
      productName?: string
      sellerName?: string
      orderStatus?: string
      paymentStatus?: string
      /** Format: int64 */
      itemsAmount?: number
      /** Format: int64 */
      shippingAmount?: number
      /** Format: int64 */
      totalAmount?: number
      /** Format: date-time */
      orderedAt?: string
    }
    ApiResponseSellerOrderDetailResponse: {
      success?: boolean
      data?: components['schemas']['SellerOrderDetailResponse']
      message?: string
    }
    OrderItemResponse: {
      productName?: string
      optionName?: string
      /** Format: int64 */
      unitPrice?: number
      /** Format: int32 */
      quantity?: number
      /** Format: int64 */
      subtotal?: number
    }
    OrderShippingResponse: {
      /** @enum {string} */
      status?:
        | 'PAYMENT_PENDING'
        | 'PAID'
        | 'PREPARING'
        | 'SHIPPED'
        | 'DELIVERED'
        | 'EXPIRED'
        | 'CANCELED'
      carrier?: string
      trackingNumber?: string
      /** Format: date-time */
      deliveredAt?: string
    }
    SellerOrderDetailResponse: {
      /** Format: uuid */
      orderId?: string
      orderNumber?: string
      /** @enum {string} */
      status?:
        | 'PAYMENT_PENDING'
        | 'PAID'
        | 'PREPARING'
        | 'SHIPPED'
        | 'DELIVERED'
        | 'EXPIRED'
        | 'CANCELED'
      items?: components['schemas']['OrderItemResponse'][]
      /** Format: int64 */
      itemsAmount?: number
      /** Format: int64 */
      shippingAmount?: number
      /** Format: int64 */
      totalAmount?: number
      /** @enum {string} */
      paymentStatus?:
        'PENDING' | 'SUCCEEDED' | 'FAILED' | 'UNKNOWN' | 'CANCELED'
      shipping?: components['schemas']['OrderShippingResponse']
      /** Format: date-time */
      orderedAt?: string
    }
    ApiResponsePageResponseSellerDropListResponse: {
      success?: boolean
      data?: components['schemas']['PageResponseSellerDropListResponse']
      message?: string
    }
    PageResponseSellerDropListResponse: {
      content?: components['schemas']['SellerDropListResponse'][]
      /** Format: int32 */
      page?: number
      /** Format: int32 */
      size?: number
      /** Format: int64 */
      totalElements?: number
      /** Format: int32 */
      totalPages?: number
      hasNext?: boolean
    }
    SellerDropListResponse: {
      /** Format: int64 */
      dropId?: number
      name?: string
      thumbnailUrl?: string
      /** @enum {string} */
      status?: 'DRAFT' | 'WISH' | 'GRAB' | 'ENDED' | 'CANCELED'
      /** Format: int64 */
      minPrice?: number
      /** Format: date-time */
      createdAt?: string
    }
    ApiResponseSellerDropDetailResponse: {
      success?: boolean
      data?: components['schemas']['SellerDropDetailResponse']
      message?: string
    }
    DropOptionGroupResponse: {
      /** Format: int64 */
      groupId?: number
      name?: string
      /** Format: int32 */
      sortOrder?: number
      values?: components['schemas']['Value'][]
    }
    DropOptionSelectionResponse: {
      /** Format: int64 */
      groupId?: number
      /** Format: int64 */
      valueId?: number
    }
    DropShippingResponse: {
      /** Format: int64 */
      shippingFee?: number
      shippingNotice?: string
    }
    Image: {
      /** Format: uuid */
      imageId?: string
      imageUrl?: string
    }
    Option: {
      /** Format: int64 */
      optionId?: number
      selections?: components['schemas']['DropOptionSelectionResponse'][]
      /** Format: int64 */
      unitPrice?: number
      /** Format: int32 */
      totalQuantity?: number
      /** Format: int32 */
      reservedQuantity?: number
      /** Format: int32 */
      soldQuantity?: number
      active?: boolean
      /** Format: int32 */
      sortOrder?: number
    }
    SellerDropDetailResponse: {
      /** Format: int64 */
      dropId?: number
      name?: string
      description?: string
      images?: components['schemas']['Image'][]
      /** Format: int64 */
      minPrice?: number
      /** Format: int64 */
      categoryId?: number
      /** @enum {string} */
      status?: 'DRAFT' | 'WISH' | 'GRAB' | 'ENDED' | 'CANCELED'
      /** Format: date-time */
      saleStartsAt?: string
      /** Format: date-time */
      saleEndsAt?: string
      shipping?: components['schemas']['DropShippingResponse']
      optionGroups?: components['schemas']['DropOptionGroupResponse'][]
      options?: components['schemas']['Option'][]
    }
    Value: {
      /** Format: int64 */
      valueId?: number
      value?: string
      /** Format: int32 */
      sortOrder?: number
    }
    ApiResponseSellerDropWishCountResponse: {
      success?: boolean
      data?: components['schemas']['SellerDropWishCountResponse']
      message?: string
    }
    SellerDropWishCountResponse: {
      /** Format: int64 */
      dropId?: number
      /** Format: int64 */
      activeWishCount?: number
    }
    ApiResponseSellerDropStockResponse: {
      success?: boolean
      data?: components['schemas']['SellerDropStockResponse']
      message?: string
    }
    SellerDropStockResponse: {
      /** Format: int64 */
      dropId?: number
      options?: components['schemas']['Option'][]
    }
    ApiResponseListUpcomingDropResponse: {
      success?: boolean
      data?: components['schemas']['UpcomingDropResponse'][]
      message?: string
    }
    UpcomingDropResponse: {
      /** Format: int64 */
      dropId?: number
      name?: string
      status?: string
      /** @enum {string} */
      eventType?: 'START' | 'END'
      /** Format: date-time */
      upcomingAt?: string
    }
    ApiResponseSellerDashboardSummaryResponse: {
      success?: boolean
      data?: components['schemas']['SellerDashboardSummaryResponse']
      message?: string
    }
    SellerDashboardSummaryResponse: {
      dropCounts?: {
        [key: string]: number
      }
      orderCounts?: {
        [key: string]: number
      }
      paymentCounts?: {
        [key: string]: number
      }
      /** Format: int64 */
      reconciliationRequired?: number
      stockSummary?: components['schemas']['StockSummary']
    }
    StockSummary: {
      /** Format: int64 */
      available?: number
      /** Format: int64 */
      reserved?: number
      /** Format: int64 */
      sold?: number
    }
    ApiResponsePageResponseDropStatsResponse: {
      success?: boolean
      data?: components['schemas']['PageResponseDropStatsResponse']
      message?: string
    }
    DropStatsResponse: {
      /** Format: int64 */
      dropId?: number
      name?: string
      status?: string
      /** Format: date-time */
      saleEndsAt?: string
      /** Format: int64 */
      activeWishCount?: number
      /** Format: int64 */
      availableStock?: number
      /** Format: int64 */
      reservedStock?: number
      /** Format: int64 */
      soldStock?: number
      /** Format: int64 */
      orderCount?: number
      /** Format: int64 */
      salesAmount?: number
    }
    PageResponseDropStatsResponse: {
      content?: components['schemas']['DropStatsResponse'][]
      /** Format: int32 */
      page?: number
      /** Format: int32 */
      size?: number
      /** Format: int64 */
      totalElements?: number
      /** Format: int32 */
      totalPages?: number
      hasNext?: boolean
    }
    ApiResponsePageResponseMyOrderListResponse: {
      success?: boolean
      data?: components['schemas']['PageResponseMyOrderListResponse']
      message?: string
    }
    MyOrderListResponse: {
      /** Format: uuid */
      orderId?: string
      orderNumber?: string
      productName?: string
      /** @enum {string} */
      status?:
        | 'PAYMENT_PENDING'
        | 'PAID'
        | 'PREPARING'
        | 'SHIPPED'
        | 'DELIVERED'
        | 'EXPIRED'
        | 'CANCELED'
      /** Format: int64 */
      totalAmount?: number
      /** Format: date-time */
      orderedAt?: string
    }
    PageResponseMyOrderListResponse: {
      content?: components['schemas']['MyOrderListResponse'][]
      /** Format: int32 */
      page?: number
      /** Format: int32 */
      size?: number
      /** Format: int64 */
      totalElements?: number
      /** Format: int32 */
      totalPages?: number
      hasNext?: boolean
    }
    ApiResponseMyOrderDetailResponse: {
      success?: boolean
      data?: components['schemas']['MyOrderDetailResponse']
      message?: string
    }
    MyOrderDetailResponse: {
      /** Format: uuid */
      orderId?: string
      orderNumber?: string
      /** @enum {string} */
      status?:
        | 'PAYMENT_PENDING'
        | 'PAID'
        | 'PREPARING'
        | 'SHIPPED'
        | 'DELIVERED'
        | 'EXPIRED'
        | 'CANCELED'
      items?: components['schemas']['OrderItemResponse'][]
      /** Format: int64 */
      itemsAmount?: number
      /** Format: int64 */
      shippingAmount?: number
      /** Format: int64 */
      totalAmount?: number
      /** @enum {string} */
      paymentStatus?:
        'PENDING' | 'SUCCEEDED' | 'FAILED' | 'UNKNOWN' | 'CANCELED'
      /** Format: date-time */
      paymentExpiresAt?: string
      shipping?: components['schemas']['OrderShippingResponse']
      /** Format: date-time */
      orderedAt?: string
    }
    ApiResponsePageResponsePublicDropListResponse: {
      success?: boolean
      data?: components['schemas']['PageResponsePublicDropListResponse']
      message?: string
    }
    DropCategoryResponse: {
      /** Format: int64 */
      categoryId?: number
      name?: string
    }
    PageResponsePublicDropListResponse: {
      content?: components['schemas']['PublicDropListResponse'][]
      /** Format: int32 */
      page?: number
      /** Format: int32 */
      size?: number
      /** Format: int64 */
      totalElements?: number
      /** Format: int32 */
      totalPages?: number
      hasNext?: boolean
    }
    PublicDropListResponse: {
      /** Format: int64 */
      dropId?: number
      name?: string
      thumbnailUrl?: string
      /** Format: int64 */
      minPrice?: number
      category?: components['schemas']['DropCategoryResponse']
      /** @enum {string} */
      status?: 'DRAFT' | 'WISH' | 'GRAB' | 'ENDED' | 'CANCELED'
      soldOut?: boolean
      /** Format: int64 */
      wishCount?: number
      /** Format: date-time */
      saleStartsAt?: string
      /** Format: date-time */
      saleEndsAt?: string
    }
    Actions: {
      wishable?: boolean
      wishCancelable?: boolean
      orderable?: boolean
    }
    ApiResponsePublicDropDetailResponse: {
      success?: boolean
      data?: components['schemas']['PublicDropDetailResponse']
      message?: string
    }
    PublicDropDetailResponse: {
      /** Format: int64 */
      dropId?: number
      name?: string
      description?: string
      imageUrls?: string[]
      /** Format: int64 */
      minPrice?: number
      category?: components['schemas']['DropCategoryResponse']
      /** @enum {string} */
      status?: 'DRAFT' | 'WISH' | 'GRAB' | 'ENDED' | 'CANCELED'
      soldOut?: boolean
      /** Format: int64 */
      wishCount?: number
      wishNotice?: string
      /** Format: date-time */
      saleStartsAt?: string
      /** Format: date-time */
      saleEndsAt?: string
      shipping?: components['schemas']['DropShippingResponse']
      optionGroups?: components['schemas']['DropOptionGroupResponse'][]
      options?: components['schemas']['Option'][]
      actions?: components['schemas']['Actions']
      /** Format: date-time */
      serverTime?: string
    }
    ApiResponsePublicDropStockResponse: {
      success?: boolean
      data?: components['schemas']['PublicDropStockResponse']
      message?: string
    }
    PublicDropStockResponse: {
      /** Format: int64 */
      dropId?: number
      options?: components['schemas']['Option'][]
      /** Format: date-time */
      serverTime?: string
    }
    ApiResponseListCategoryResponse: {
      success?: boolean
      data?: components['schemas']['CategoryResponse'][]
      message?: string
    }
    CategoryResponse: {
      /** Format: int64 */
      categoryId?: number
      code?: string
      name?: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  register: {
    parameters: {
      query?: never
      header?: never
      path: {
        dropId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseWishResponse']
        }
      }
    }
  }
  cancel: {
    parameters: {
      query?: never
      header?: never
      path: {
        dropId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  issuePresignedUrl: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ImageUploadUrlRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseImageUploadUrlResponse']
        }
      }
    }
  }
  registerShipment: {
    parameters: {
      query?: never
      header?: {
        'Idempotency-Key'?: string
      }
      path: {
        orderId: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ShipmentRegisterRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseOrderStatusResponse']
        }
      }
    }
  }
  updateShipment: {
    parameters: {
      query?: never
      header?: never
      path: {
        orderId: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ShipmentRegisterRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseShipmentUpdateResponse']
        }
      }
    }
  }
  prepareShipment: {
    parameters: {
      query?: never
      header?: never
      path: {
        orderId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseOrderStatusResponse']
        }
      }
    }
  }
  listDrops: {
    parameters: {
      query?: {
        status?: 'DRAFT' | 'WISH' | 'GRAB' | 'ENDED' | 'CANCELED'
        page?: number
        size?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponsePageResponseSellerDropListResponse']
        }
      }
    }
  }
  createDraft: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['DropDraftRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseDropDraftResponse']
        }
      }
    }
  }
  publish: {
    parameters: {
      query?: never
      header?: never
      path: {
        dropId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseDropPublishResponse']
        }
      }
    }
  }
  cancel_1: {
    parameters: {
      query?: never
      header?: never
      path: {
        dropId: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['DropCancelRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseDropCancelResponse']
        }
      }
    }
  }
  findMyOrders: {
    parameters: {
      query?: {
        status?:
          | 'PAYMENT_PENDING'
          | 'PAID'
          | 'PREPARING'
          | 'SHIPPED'
          | 'DELIVERED'
          | 'EXPIRED'
          | 'CANCELED'
        page?: number
        size?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponsePageResponseMyOrderListResponse']
        }
      }
    }
  }
  create: {
    parameters: {
      query?: never
      header?: {
        'Idempotency-Key'?: string
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['OrderCreateRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseOrderCreateResponse']
        }
      }
    }
  }
  pay: {
    parameters: {
      query?: never
      header?: {
        'Idempotency-Key'?: string
      }
      path: {
        orderId: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PaymentRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponsePaymentResponse']
        }
      }
    }
  }
  cancel_2: {
    parameters: {
      query?: never
      header?: {
        'Idempotency-Key'?: string
      }
      path: {
        orderId: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['OrderCancelRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseOrderCancelResponse']
        }
      }
    }
  }
  requestCode: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['EmailVerificationRequest']
      }
    }
    responses: {
      /** @description 요청 처리 완료 */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description INVALID_REQUEST, VALIDATION_FAILED, INVALID_EMAIL */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description EMAIL_VERIFICATION_RESEND_TOO_SOON */
      429: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  confirmCode: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['EmailVerificationConfirmRequest']
      }
    }
    responses: {
      /** @description 확인 성공, Set-Cookie로 가입 토큰 발급 */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description INVALID_REQUEST, VALIDATION_FAILED, INVALID_EMAIL, EMAIL_VERIFICATION_CODE_MISMATCH, EMAIL_VERIFICATION_CODE_EXPIRED */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description DUPLICATE_EMAIL */
      409: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description EMAIL_VERIFICATION_ATTEMPTS_EXCEEDED */
      429: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  findDrop: {
    parameters: {
      query?: never
      header?: never
      path: {
        dropId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseSellerDropDetailResponse']
        }
      }
    }
  }
  updateDraft: {
    parameters: {
      query?: never
      header?: never
      path: {
        dropId: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['DropDraftRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseDropDraftResponse']
        }
      }
    }
  }
  listMyWishes: {
    parameters: {
      query?: {
        page?: number
        size?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponsePageResponseWishListResponse']
        }
      }
    }
  }
  listOrders: {
    parameters: {
      query?: {
        dropId?: number
        orderStatus?:
          | 'PAYMENT_PENDING'
          | 'PAID'
          | 'PREPARING'
          | 'SHIPPED'
          | 'DELIVERED'
          | 'EXPIRED'
          | 'CANCELED'
        paymentStatus?:
          'PENDING' | 'SUCCEEDED' | 'FAILED' | 'UNKNOWN' | 'CANCELED'
        page?: number
        size?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponsePageResponseSellerOrderListResponse']
        }
      }
    }
  }
  findOrder: {
    parameters: {
      query?: never
      header?: never
      path: {
        orderId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseSellerOrderDetailResponse']
        }
      }
    }
  }
  findWishCount: {
    parameters: {
      query?: never
      header?: never
      path: {
        dropId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseSellerDropWishCountResponse']
        }
      }
    }
  }
  findStocks: {
    parameters: {
      query?: never
      header?: never
      path: {
        dropId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseSellerDropStockResponse']
        }
      }
    }
  }
  findUpcomingDrops: {
    parameters: {
      query?: {
        eventType?: 'START' | 'END'
        withinMinutes?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseListUpcomingDropResponse']
        }
      }
    }
  }
  findSummary: {
    parameters: {
      query?: {
        from?: string
        to?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseSellerDashboardSummaryResponse']
        }
      }
    }
  }
  findDropStats: {
    parameters: {
      query?: {
        status?: 'DRAFT' | 'WISH' | 'GRAB' | 'ENDED' | 'CANCELED'
        page?: number
        size?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponsePageResponseDropStatsResponse']
        }
      }
    }
  }
  findMyOrder: {
    parameters: {
      query?: never
      header?: never
      path: {
        orderId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseMyOrderDetailResponse']
        }
      }
    }
  }
  listDrops_1: {
    parameters: {
      query?: {
        status?: 'DRAFT' | 'WISH' | 'GRAB' | 'ENDED' | 'CANCELED'
        categoryId?: number
        keyword?: string
        soldOut?: boolean
        sort?: string
        page?: number
        size?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponsePageResponsePublicDropListResponse']
        }
      }
    }
  }
  getDrop: {
    parameters: {
      query?: never
      header?: never
      path: {
        dropId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponsePublicDropDetailResponse']
        }
      }
    }
  }
  getStocks: {
    parameters: {
      query?: never
      header?: never
      path: {
        dropId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponsePublicDropStockResponse']
        }
      }
    }
  }
  listCategories: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseListCategoryResponse']
        }
      }
    }
  }
}
