-- DROP 단위 메일 알림 발송 기록(GR-69).
-- 상태 전환이 없는 알림(판매 시작 10분 전 등)은 중복 발송을 막을 토큰이 없어, 이 테이블의 유니크 제약을 토큰으로 쓴다.
-- INSERT ... ON CONFLICT DO NOTHING RETURNING으로 선점에 성공한 인스턴스만 발송한다.
-- 수신자별 행이 아니라 DROP 1건당 1행이다. 인앱 알림 목록은 범위 밖이다(ERD.md 0절).
CREATE TABLE drop_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    drop_id BIGINT NOT NULL,
    type VARCHAR(30) NOT NULL,
    sent_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_drop_notifications PRIMARY KEY (id),
    CONSTRAINT uq_drop_notifications_drop_type UNIQUE (drop_id, type),
    CONSTRAINT fk_drop_notifications_drop FOREIGN KEY (drop_id) REFERENCES drops (id),
    CONSTRAINT ck_drop_notifications_type CHECK (type IN ('PRESALE_10M'))
);
