CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(254) NOT NULL,
    password_hash VARCHAR(255),
    display_name VARCHAR(100) NOT NULL,
    phone VARCHAR(30) NOT NULL,
    profile_image_url VARCHAR(500),
    role VARCHAR(20) NOT NULL DEFAULT 'USER',
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    provider VARCHAR(20) NOT NULL DEFAULT 'LOCAL',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('USER', 'ADMIN')),
    CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'SUSPENDED', 'WITHDRAWN')),
    CONSTRAINT ck_users_provider CHECK (provider IN ('LOCAL', 'KAKAO', 'GOOGLE')),
    CONSTRAINT ck_users_local_password CHECK (provider <> 'LOCAL' OR password_hash IS NOT NULL)
);

CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id),
    CONSTRAINT uq_refresh_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_refresh_tokens_expiry CHECK (expires_at > created_at),
    CONSTRAINT ck_refresh_tokens_revocation CHECK (revoked_at IS NULL OR revoked_at >= created_at)
);

CREATE TABLE sellers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    brand_name VARCHAR(100) NOT NULL,
    contact_email VARCHAR(254) NOT NULL,
    description TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    submitted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_by BIGINT,
    reviewed_at TIMESTAMPTZ,
    rejection_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_sellers PRIMARY KEY (id),
    CONSTRAINT uq_sellers_user UNIQUE (user_id),
    CONSTRAINT fk_sellers_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_sellers_reviewer FOREIGN KEY (reviewed_by) REFERENCES users (id),
    CONSTRAINT ck_sellers_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    CONSTRAINT ck_sellers_review CHECK (
        (status = 'PENDING' AND reviewed_by IS NULL AND reviewed_at IS NULL AND rejection_reason IS NULL)
        OR (status = 'APPROVED' AND reviewed_by IS NOT NULL AND reviewed_at IS NOT NULL AND rejection_reason IS NULL)
        OR (status = 'REJECTED' AND reviewed_by IS NOT NULL AND reviewed_at IS NOT NULL AND rejection_reason IS NOT NULL)
    )
);

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_categories PRIMARY KEY (id),
    CONSTRAINT uq_categories_code UNIQUE (code)
);

CREATE TABLE drops (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    seller_id BIGINT NOT NULL,
    category_id BIGINT,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    name VARCHAR(200),
    description TEXT,
    shipping_fee BIGINT,
    shipping_notice TEXT,
    sale_starts_at TIMESTAMPTZ,
    sale_ends_at TIMESTAMPTZ,
    published_at TIMESTAMPTZ,
    grab_started_at TIMESTAMPTZ,
    closed_at TIMESTAMPTZ,
    close_reason VARCHAR(30),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_drops PRIMARY KEY (id),
    CONSTRAINT fk_drops_seller FOREIGN KEY (seller_id) REFERENCES sellers (id),
    CONSTRAINT fk_drops_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT ck_drops_status CHECK (status IN ('DRAFT', 'WISH', 'GRAB', 'ENDED', 'CANCELED')),
    CONSTRAINT ck_drops_shipping_fee CHECK (shipping_fee IS NULL OR shipping_fee >= 0),
    CONSTRAINT ck_drops_sale_period CHECK (
        sale_starts_at IS NULL OR sale_ends_at IS NULL OR sale_starts_at < sale_ends_at
    ),
    CONSTRAINT ck_drops_close_reason CHECK (
        close_reason IS NULL OR close_reason IN ('TIME_EXPIRED', 'SOLD_OUT', 'SELLER_CANCELED')
    ),
    CONSTRAINT ck_drops_published_fields CHECK (
        status NOT IN ('WISH', 'GRAB', 'ENDED')
        OR (
            category_id IS NOT NULL
            AND name IS NOT NULL
            AND description IS NOT NULL
            AND shipping_fee IS NOT NULL
            AND shipping_notice IS NOT NULL
            AND sale_starts_at IS NOT NULL
            AND sale_ends_at IS NOT NULL
            AND published_at IS NOT NULL
        )
    ),
    CONSTRAINT ck_drops_grab_started_at CHECK (
        status NOT IN ('GRAB', 'ENDED') OR grab_started_at IS NOT NULL
    ),
    CONSTRAINT ck_drops_closed CHECK (
        status NOT IN ('ENDED', 'CANCELED') OR (closed_at IS NOT NULL AND close_reason IS NOT NULL)
    )
);

CREATE TABLE drop_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    drop_id BIGINT NOT NULL,
    image_url VARCHAR(500) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    alt_text VARCHAR(300) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_drop_images PRIMARY KEY (id),
    CONSTRAINT uq_drop_images_sort UNIQUE (drop_id, sort_order),
    CONSTRAINT fk_drop_images_drop FOREIGN KEY (drop_id) REFERENCES drops (id),
    CONSTRAINT ck_drop_images_sort CHECK (sort_order >= 0)
);

CREATE TABLE drop_option_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    drop_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_drop_option_groups PRIMARY KEY (id),
    CONSTRAINT uq_drop_option_groups_name UNIQUE (drop_id, name),
    CONSTRAINT uq_drop_option_groups_id_drop UNIQUE (id, drop_id),
    CONSTRAINT fk_drop_option_groups_drop FOREIGN KEY (drop_id) REFERENCES drops (id),
    CONSTRAINT ck_drop_option_groups_sort CHECK (sort_order >= 0)
);

CREATE TABLE drop_option_values (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    group_id BIGINT NOT NULL,
    value VARCHAR(100) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_drop_option_values PRIMARY KEY (id),
    CONSTRAINT uq_drop_option_values_value UNIQUE (group_id, value),
    CONSTRAINT uq_drop_option_values_id_group UNIQUE (id, group_id),
    CONSTRAINT fk_drop_option_values_group FOREIGN KEY (group_id) REFERENCES drop_option_groups (id),
    CONSTRAINT ck_drop_option_values_sort CHECK (sort_order >= 0)
);

CREATE TABLE drop_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    drop_id BIGINT NOT NULL,
    unit_price BIGINT NOT NULL,
    total_quantity INT NOT NULL,
    reserved_quantity INT NOT NULL DEFAULT 0,
    sold_quantity INT NOT NULL DEFAULT 0,
    withheld_quantity INT NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_drop_options PRIMARY KEY (id),
    CONSTRAINT uq_drop_options_id_drop UNIQUE (id, drop_id),
    CONSTRAINT fk_drop_options_drop FOREIGN KEY (drop_id) REFERENCES drops (id),
    CONSTRAINT ck_drop_options_price CHECK (unit_price >= 0),
    CONSTRAINT ck_drop_options_quantities CHECK (
        total_quantity >= 0
        AND reserved_quantity >= 0
        AND sold_quantity >= 0
        AND withheld_quantity >= 0
        AND reserved_quantity + sold_quantity + withheld_quantity <= total_quantity
    ),
    CONSTRAINT ck_drop_options_sort CHECK (sort_order >= 0)
);

CREATE TABLE drop_option_value_maps (
    option_id BIGINT NOT NULL,
    group_id BIGINT NOT NULL,
    value_id BIGINT NOT NULL,
    drop_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_drop_option_value_maps PRIMARY KEY (option_id, group_id),
    CONSTRAINT fk_option_maps_option FOREIGN KEY (option_id, drop_id)
        REFERENCES drop_options (id, drop_id),
    CONSTRAINT fk_option_maps_group FOREIGN KEY (group_id, drop_id)
        REFERENCES drop_option_groups (id, drop_id),
    CONSTRAINT fk_option_maps_value FOREIGN KEY (value_id, group_id)
        REFERENCES drop_option_values (id, group_id)
);

CREATE TABLE wishes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    drop_id BIGINT NOT NULL,
    activated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    canceled_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_wishes PRIMARY KEY (id),
    CONSTRAINT uq_wishes_user_drop UNIQUE (user_id, drop_id),
    CONSTRAINT fk_wishes_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_wishes_drop FOREIGN KEY (drop_id) REFERENCES drops (id),
    CONSTRAINT ck_wishes_canceled_at CHECK (canceled_at IS NULL OR canceled_at >= activated_at)
);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_number VARCHAR(64) NOT NULL,
    buyer_id BIGINT NOT NULL,
    drop_id BIGINT NOT NULL,
    idempotency_key VARCHAR(100) NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PAYMENT_PENDING',
    product_name_snapshot VARCHAR(200) NOT NULL,
    seller_name_snapshot VARCHAR(100) NOT NULL,
    items_amount BIGINT NOT NULL,
    shipping_amount BIGINT NOT NULL,
    total_amount BIGINT NOT NULL,
    recipient_name VARCHAR(100) NOT NULL,
    recipient_phone VARCHAR(30) NOT NULL,
    postal_code VARCHAR(20) NOT NULL,
    address_line1 VARCHAR(300) NOT NULL,
    address_line2 VARCHAR(300),
    delivery_memo VARCHAR(300),
    payment_expires_at TIMESTAMPTZ NOT NULL,
    paid_at TIMESTAMPTZ,
    canceled_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_orders PRIMARY KEY (id),
    CONSTRAINT uq_orders_order_number UNIQUE (order_number),
    CONSTRAINT uq_orders_buyer_idempotency UNIQUE (buyer_id, idempotency_key),
    CONSTRAINT uq_orders_id_drop UNIQUE (id, drop_id),
    CONSTRAINT fk_orders_buyer FOREIGN KEY (buyer_id) REFERENCES users (id),
    CONSTRAINT fk_orders_drop FOREIGN KEY (drop_id) REFERENCES drops (id),
    CONSTRAINT ck_orders_status CHECK (
        status IN ('PAYMENT_PENDING', 'PAID', 'EXPIRED', 'PREPARING', 'SHIPPED', 'DELIVERED', 'CANCELED')
    ),
    CONSTRAINT ck_orders_amounts CHECK (
        items_amount >= 0
        AND shipping_amount >= 0
        AND total_amount = items_amount + shipping_amount
    ),
    CONSTRAINT ck_orders_payment_expiry CHECK (payment_expires_at > created_at),
    CONSTRAINT ck_orders_paid_at CHECK (
        status NOT IN ('PAID', 'PREPARING', 'SHIPPED', 'DELIVERED') OR paid_at IS NOT NULL
    ),
    CONSTRAINT ck_orders_canceled_at CHECK (status <> 'CANCELED' OR canceled_at IS NOT NULL)
);

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT NOT NULL,
    drop_id BIGINT NOT NULL,
    option_id BIGINT NOT NULL,
    option_name_snapshot VARCHAR(200) NOT NULL,
    unit_price BIGINT NOT NULL,
    quantity INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_order_items PRIMARY KEY (id),
    CONSTRAINT uq_order_items_order_option UNIQUE (order_id, option_id),
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id, drop_id)
        REFERENCES orders (id, drop_id),
    CONSTRAINT fk_order_items_option FOREIGN KEY (option_id, drop_id)
        REFERENCES drop_options (id, drop_id),
    CONSTRAINT ck_order_items_price CHECK (unit_price >= 0),
    CONSTRAINT ck_order_items_quantity CHECK (quantity > 0)
);

CREATE TABLE stock_reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_item_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'HELD',
    expires_at TIMESTAMPTZ NOT NULL,
    committed_at TIMESTAMPTZ,
    released_at TIMESTAMPTZ,
    release_reason VARCHAR(30),
    release_destination VARCHAR(20),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_stock_reservations PRIMARY KEY (id),
    CONSTRAINT uq_stock_reservations_order_item UNIQUE (order_item_id),
    CONSTRAINT fk_stock_reservations_item FOREIGN KEY (order_item_id) REFERENCES order_items (id),
    CONSTRAINT ck_stock_reservations_status CHECK (status IN ('HELD', 'COMMITTED', 'RELEASED')),
    CONSTRAINT ck_stock_reservations_expiry CHECK (expires_at > created_at),
    CONSTRAINT ck_stock_reservations_release_reason CHECK (
        release_reason IS NULL OR release_reason IN ('PAYMENT_FAILED', 'EXPIRED', 'ORDER_CANCELED')
    ),
    CONSTRAINT ck_stock_reservations_destination CHECK (
        release_destination IS NULL OR release_destination IN ('AVAILABLE', 'WITHHELD')
    ),
    CONSTRAINT ck_stock_reservations_state_fields CHECK (
        (status = 'HELD' AND committed_at IS NULL AND released_at IS NULL
            AND release_reason IS NULL AND release_destination IS NULL)
        OR (status = 'COMMITTED' AND committed_at IS NOT NULL AND released_at IS NULL
            AND release_reason IS NULL AND release_destination IS NULL)
        OR (status = 'RELEASED' AND released_at IS NOT NULL
            AND release_reason IS NOT NULL AND release_destination IS NOT NULL)
    )
);

CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT NOT NULL,
    provider VARCHAR(30) NOT NULL,
    idempotency_key VARCHAR(100) NOT NULL,
    provider_payment_id VARCHAR(200),
    amount BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    reconciliation_status VARCHAR(20) NOT NULL DEFAULT 'NONE',
    reconciliation_reason TEXT,
    approved_at TIMESTAMPTZ,
    canceled_at TIMESTAMPTZ,
    failure_code VARCHAR(100),
    failure_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_payments PRIMARY KEY (id),
    CONSTRAINT uq_payments_idempotency UNIQUE (provider, idempotency_key),
    CONSTRAINT uq_payments_provider_payment UNIQUE (provider, provider_payment_id),
    CONSTRAINT fk_payments_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT ck_payments_provider CHECK (provider IN ('MOCK', 'TOSS')),
    CONSTRAINT ck_payments_amount CHECK (amount >= 0),
    CONSTRAINT ck_payments_status CHECK (
        status IN ('PENDING', 'SUCCEEDED', 'FAILED', 'UNKNOWN', 'CANCELED')
    ),
    CONSTRAINT ck_payments_reconciliation CHECK (
        reconciliation_status IN ('NONE', 'REQUIRED', 'RESOLVED')
    ),
    CONSTRAINT ck_payments_approved_at CHECK (
        status NOT IN ('SUCCEEDED', 'CANCELED') OR approved_at IS NOT NULL
    ),
    CONSTRAINT ck_payments_canceled_at CHECK (status <> 'CANCELED' OR canceled_at IS NOT NULL),
    CONSTRAINT ck_payments_unknown_reconciliation CHECK (
        status <> 'UNKNOWN' OR reconciliation_status = 'REQUIRED'
    )
);

CREATE TABLE payment_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    payment_id BIGINT NOT NULL,
    event_key VARCHAR(200) NOT NULL,
    event_type VARCHAR(40) NOT NULL,
    source VARCHAR(20) NOT NULL,
    processing_result VARCHAR(30) NOT NULL,
    payload JSONB NOT NULL,
    occurred_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_payment_events PRIMARY KEY (id),
    CONSTRAINT uq_payment_events_key UNIQUE (payment_id, event_key),
    CONSTRAINT fk_payment_events_payment FOREIGN KEY (payment_id) REFERENCES payments (id),
    CONSTRAINT ck_payment_events_source CHECK (source IN ('API', 'WEBHOOK', 'RECONCILIATION')),
    CONSTRAINT ck_payment_events_result CHECK (
        processing_result IN ('APPLIED', 'REJECTED', 'RECONCILIATION_REQUIRED')
    )
);

CREATE TABLE payment_cancellations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    payment_id BIGINT NOT NULL,
    requested_by BIGINT,
    purpose VARCHAR(30) NOT NULL,
    idempotency_key VARCHAR(100) NOT NULL,
    amount BIGINT NOT NULL,
    reason TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'REQUESTED',
    provider_cancel_id VARCHAR(200),
    completed_at TIMESTAMPTZ,
    failure_code VARCHAR(100),
    attempt_count INT NOT NULL DEFAULT 0,
    next_retry_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_payment_cancellations PRIMARY KEY (id),
    CONSTRAINT uq_payment_cancellations_idempotency UNIQUE (idempotency_key),
    CONSTRAINT fk_payment_cancellations_payment FOREIGN KEY (payment_id) REFERENCES payments (id),
    CONSTRAINT fk_payment_cancellations_requester FOREIGN KEY (requested_by) REFERENCES users (id),
    CONSTRAINT ck_payment_cancellations_purpose CHECK (
        purpose IN ('ORDER_CANCEL', 'LATE_APPROVAL_COMPENSATION')
    ),
    CONSTRAINT ck_payment_cancellations_amount CHECK (amount >= 0),
    CONSTRAINT ck_payment_cancellations_status CHECK (
        status IN ('REQUESTED', 'UNKNOWN', 'SUCCEEDED', 'FAILED')
    ),
    CONSTRAINT ck_payment_cancellations_attempts CHECK (attempt_count >= 0),
    CONSTRAINT ck_payment_cancellations_completed CHECK (
        status NOT IN ('SUCCEEDED', 'FAILED') OR completed_at IS NOT NULL
    )
);

CREATE TABLE shipments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT NOT NULL,
    carrier_code VARCHAR(50) NOT NULL,
    tracking_number VARCHAR(100) NOT NULL,
    shipped_at TIMESTAMPTZ,
    delivered_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_shipments PRIMARY KEY (id),
    CONSTRAINT uq_shipments_order UNIQUE (order_id),
    CONSTRAINT fk_shipments_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT ck_shipments_delivery_time CHECK (
        delivered_at IS NULL OR (shipped_at IS NOT NULL AND delivered_at >= shipped_at)
    )
);

CREATE INDEX idx_refresh_tokens_user_active
    ON refresh_tokens (user_id, revoked_at, expires_at);

CREATE INDEX idx_sellers_review_queue
    ON sellers (status, submitted_at, id);

CREATE INDEX idx_drops_public_list
    ON drops (status, category_id, published_at, id);

CREATE INDEX idx_drops_seller_status
    ON drops (seller_id, status, id);

CREATE INDEX idx_drops_sale_start
    ON drops (status, sale_starts_at);

CREATE INDEX idx_drops_sale_end
    ON drops (status, sale_ends_at);

CREATE INDEX idx_drop_options_drop_active
    ON drop_options (drop_id, is_active, id);

CREATE INDEX idx_wishes_drop_active
    ON wishes (drop_id, canceled_at, id);

CREATE INDEX idx_wishes_user_activated
    ON wishes (user_id, activated_at, id);

CREATE INDEX idx_orders_buyer_created
    ON orders (buyer_id, created_at, id);

CREATE INDEX idx_orders_drop_status
    ON orders (drop_id, status, id);

CREATE INDEX idx_orders_payment_expiry
    ON orders (status, payment_expires_at, id);

CREATE INDEX idx_payments_order_created
    ON payments (order_id, created_at, id);

CREATE INDEX idx_payments_reconciliation
    ON payments (reconciliation_status, updated_at, id);

CREATE INDEX idx_payment_cancellations_retry
    ON payment_cancellations (status, next_retry_at, id);
