CREATE TABLE order_cancellation_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT NOT NULL,
    buyer_id BIGINT NOT NULL,
    idempotency_key VARCHAR(100) NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    reason VARCHAR(300) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_order_cancellation_requests PRIMARY KEY (id),
    CONSTRAINT uq_order_cancellation_buyer_key UNIQUE (buyer_id, idempotency_key),
    CONSTRAINT fk_order_cancellation_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT fk_order_cancellation_buyer FOREIGN KEY (buyer_id) REFERENCES users (id)
);

CREATE INDEX idx_order_cancellation_order
    ON order_cancellation_requests (order_id, id);
