/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/seller/dashboard/upcoming-drops': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['findUpcomingDrops']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/seller/dashboard/summary': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['findSummary']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/seller/dashboard/drops': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['findDropStats']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    ApiResponseListUpcomingDropResponse: {
      success?: boolean
      data?: components['schemas']['UpcomingDropResponse'][]
      message?: string
    }
    UpcomingDropResponse: {
      /** Format: int64 */
      dropId?: number
      name?: string
      status?: string
      /** @enum {string} */
      eventType?: 'START' | 'END'
      /** Format: date-time */
      upcomingAt?: string
    }
    ApiResponseSellerDashboardSummaryResponse: {
      success?: boolean
      data?: components['schemas']['SellerDashboardSummaryResponse']
      message?: string
    }
    SellerDashboardSummaryResponse: {
      dropCounts?: {
        [key: string]: number
      }
      orderCounts?: {
        [key: string]: number
      }
      paymentCounts?: {
        [key: string]: number
      }
      /** Format: int64 */
      reconciliationRequired?: number
      stockSummary?: components['schemas']['StockSummary']
    }
    StockSummary: {
      /** Format: int64 */
      available?: number
      /** Format: int64 */
      reserved?: number
      /** Format: int64 */
      sold?: number
    }
    ApiResponsePageResponseDropStatsResponse: {
      success?: boolean
      data?: components['schemas']['PageResponseDropStatsResponse']
      message?: string
    }
    DropStatsResponse: {
      /** Format: int64 */
      dropId?: number
      name?: string
      status?: string
      /** Format: date-time */
      saleEndsAt?: string
      /** Format: int64 */
      activeWishCount?: number
      /** Format: int64 */
      availableStock?: number
      /** Format: int64 */
      reservedStock?: number
      /** Format: int64 */
      soldStock?: number
      /** Format: int64 */
      orderCount?: number
      /** Format: int64 */
      salesAmount?: number
    }
    PageResponseDropStatsResponse: {
      content?: components['schemas']['DropStatsResponse'][]
      /** Format: int32 */
      page?: number
      /** Format: int32 */
      size?: number
      /** Format: int64 */
      totalElements?: number
      /** Format: int32 */
      totalPages?: number
      hasNext?: boolean
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  findUpcomingDrops: {
    parameters: {
      query?: {
        eventType?: 'START' | 'END'
        withinMinutes?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseListUpcomingDropResponse']
        }
      }
    }
  }
  findSummary: {
    parameters: {
      query?: {
        from?: string
        to?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseSellerDashboardSummaryResponse']
        }
      }
    }
  }
  findDropStats: {
    parameters: {
      query?: {
        status?: 'DRAFT' | 'WISH' | 'GRAB' | 'ENDED' | 'CANCELED'
        page?: number
        size?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponsePageResponseDropStatsResponse']
        }
      }
    }
  }
}
