/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/uploads/images/presigned-url': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['issuePresignedUrl']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/seller/drops': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['listDrops']
    put?: never
    post: operations['createDraft']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/seller/drops/{dropId}/publish': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['publish']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/seller/drops/{dropId}/cancel': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['cancel']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/seller/drops/{dropId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['findDrop']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch: operations['updateDraft']
    trace?: never
  }
  '/api/v1/seller/drops/{dropId}/wish-count': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['findWishCount']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/seller/drops/{dropId}/stocks': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['findStocks']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/drops': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['listDrops_1']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/drops/{dropId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getDrop']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/drops/{dropId}/stocks': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getStocks']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    ImageUploadUrlRequest: {
      fileName: string
      contentType: string
      /** Format: int64 */
      fileSize: number
    }
    ApiResponseImageUploadUrlResponse: {
      success?: boolean
      data?: components['schemas']['ImageUploadUrlResponse']
      message?: string
    }
    ImageUploadUrlResponse: {
      /** Format: uuid */
      imageId?: string
      uploadUrl?: string
      imageUrl?: string
      /** Format: date-time */
      expiresAt?: string
    }
    DropDraftRequest: {
      name?: string
      description?: string
      images?: components['schemas']['DropImageRequest'][]
      /** Format: int64 */
      categoryId?: number
      /** Format: date-time */
      saleStartsAt?: string
      /** Format: date-time */
      saleEndsAt?: string
      shipping?: components['schemas']['ShippingRequest']
      optionGroups?: components['schemas']['OptionGroupRequest'][]
      options?: components['schemas']['OptionRequest'][]
    }
    DropImageRequest: {
      /** Format: uuid */
      imageId: string
      imageUrl: string
    }
    OptionGroupRequest: {
      key: string
      name: string
      /** Format: int32 */
      sortOrder?: number
      values?: components['schemas']['OptionValueRequest'][]
    }
    OptionRequest: {
      selections?: components['schemas']['SelectionRequest'][]
      /** Format: int64 */
      unitPrice: number
      /** Format: int32 */
      totalQuantity: number
      active?: boolean
      /** Format: int32 */
      sortOrder?: number
    }
    OptionValueRequest: {
      key: string
      value: string
      /** Format: int32 */
      sortOrder?: number
    }
    SelectionRequest: {
      groupKey: string
      valueKey: string
    }
    ShippingRequest: {
      /** Format: int64 */
      shippingFee?: number
      shippingNotice?: string
    }
    ApiResponseDropDraftResponse: {
      success?: boolean
      data?: components['schemas']['DropDraftResponse']
      message?: string
    }
    DropDraftResponse: {
      /** Format: int64 */
      dropId?: number
      /** @enum {string} */
      status?: 'DRAFT' | 'WISH' | 'GRAB' | 'ENDED' | 'CANCELED'
      /** Format: date-time */
      createdAt?: string
    }
    ApiResponseDropPublishResponse: {
      success?: boolean
      data?: components['schemas']['DropPublishResponse']
      message?: string
    }
    DropPublishResponse: {
      /** Format: int64 */
      dropId?: number
      /** @enum {string} */
      status?: 'DRAFT' | 'WISH' | 'GRAB' | 'ENDED' | 'CANCELED'
      /** Format: date-time */
      publishedAt?: string
    }
    DropCancelRequest: {
      reason: string
    }
    ApiResponseDropCancelResponse: {
      success?: boolean
      data?: components['schemas']['DropCancelResponse']
      message?: string
    }
    DropCancelResponse: {
      /** Format: int64 */
      dropId?: number
      /** @enum {string} */
      status?: 'DRAFT' | 'WISH' | 'GRAB' | 'ENDED' | 'CANCELED'
      /** Format: date-time */
      canceledAt?: string
    }
    ApiResponsePageResponseSellerDropListResponse: {
      success?: boolean
      data?: components['schemas']['PageResponseSellerDropListResponse']
      message?: string
    }
    PageResponseSellerDropListResponse: {
      content?: components['schemas']['SellerDropListResponse'][]
      /** Format: int32 */
      page?: number
      /** Format: int32 */
      size?: number
      /** Format: int64 */
      totalElements?: number
      /** Format: int32 */
      totalPages?: number
      hasNext?: boolean
    }
    SellerDropListResponse: {
      /** Format: int64 */
      dropId?: number
      name?: string
      thumbnailUrl?: string
      /** @enum {string} */
      status?: 'DRAFT' | 'WISH' | 'GRAB' | 'ENDED' | 'CANCELED'
      /** Format: int64 */
      minPrice?: number
      /** Format: date-time */
      createdAt?: string
    }
    ApiResponseSellerDropDetailResponse: {
      success?: boolean
      data?: components['schemas']['SellerDropDetailResponse']
      message?: string
    }
    DropOptionGroupResponse: {
      /** Format: int64 */
      groupId?: number
      name?: string
      /** Format: int32 */
      sortOrder?: number
      values?: components['schemas']['Value'][]
    }
    DropOptionSelectionResponse: {
      /** Format: int64 */
      groupId?: number
      /** Format: int64 */
      valueId?: number
    }
    DropShippingResponse: {
      /** Format: int64 */
      shippingFee?: number
      shippingNotice?: string
    }
    Image: {
      /** Format: uuid */
      imageId?: string
      imageUrl?: string
    }
    Option: {
      /** Format: int64 */
      optionId?: number
      selections?: components['schemas']['DropOptionSelectionResponse'][]
      /** Format: int64 */
      unitPrice?: number
      /** Format: int32 */
      totalQuantity?: number
      /** Format: int32 */
      reservedQuantity?: number
      /** Format: int32 */
      soldQuantity?: number
      active?: boolean
      /** Format: int32 */
      sortOrder?: number
    }
    SellerDropDetailResponse: {
      /** Format: int64 */
      dropId?: number
      name?: string
      description?: string
      images?: components['schemas']['Image'][]
      /** Format: int64 */
      minPrice?: number
      /** Format: int64 */
      categoryId?: number
      /** @enum {string} */
      status?: 'DRAFT' | 'WISH' | 'GRAB' | 'ENDED' | 'CANCELED'
      /** Format: date-time */
      saleStartsAt?: string
      /** Format: date-time */
      saleEndsAt?: string
      shipping?: components['schemas']['DropShippingResponse']
      optionGroups?: components['schemas']['DropOptionGroupResponse'][]
      options?: components['schemas']['Option'][]
    }
    Value: {
      /** Format: int64 */
      valueId?: number
      value?: string
      /** Format: int32 */
      sortOrder?: number
    }
    ApiResponseSellerDropWishCountResponse: {
      success?: boolean
      data?: components['schemas']['SellerDropWishCountResponse']
      message?: string
    }
    SellerDropWishCountResponse: {
      /** Format: int64 */
      dropId?: number
      /** Format: int64 */
      activeWishCount?: number
    }
    ApiResponseSellerDropStockResponse: {
      success?: boolean
      data?: components['schemas']['SellerDropStockResponse']
      message?: string
    }
    SellerDropStockResponse: {
      /** Format: int64 */
      dropId?: number
      options?: components['schemas']['Option'][]
    }
    ApiResponsePageResponsePublicDropListResponse: {
      success?: boolean
      data?: components['schemas']['PageResponsePublicDropListResponse']
      message?: string
    }
    DropCategoryResponse: {
      /** Format: int64 */
      categoryId?: number
      name?: string
    }
    PageResponsePublicDropListResponse: {
      content?: components['schemas']['PublicDropListResponse'][]
      /** Format: int32 */
      page?: number
      /** Format: int32 */
      size?: number
      /** Format: int64 */
      totalElements?: number
      /** Format: int32 */
      totalPages?: number
      hasNext?: boolean
    }
    PublicDropListResponse: {
      /** Format: int64 */
      dropId?: number
      name?: string
      thumbnailUrl?: string
      /** Format: int64 */
      minPrice?: number
      category?: components['schemas']['DropCategoryResponse']
      /** @enum {string} */
      status?: 'DRAFT' | 'WISH' | 'GRAB' | 'ENDED' | 'CANCELED'
      soldOut?: boolean
      /** Format: int64 */
      wishCount?: number
      /** Format: date-time */
      saleStartsAt?: string
      /** Format: date-time */
      saleEndsAt?: string
    }
    Actions: {
      wishable?: boolean
      wishCancelable?: boolean
      orderable?: boolean
    }
    ApiResponsePublicDropDetailResponse: {
      success?: boolean
      data?: components['schemas']['PublicDropDetailResponse']
      message?: string
    }
    PublicDropDetailResponse: {
      /** Format: int64 */
      dropId?: number
      name?: string
      description?: string
      imageUrls?: string[]
      /** Format: int64 */
      minPrice?: number
      category?: components['schemas']['DropCategoryResponse']
      /** @enum {string} */
      status?: 'DRAFT' | 'WISH' | 'GRAB' | 'ENDED' | 'CANCELED'
      soldOut?: boolean
      /** Format: int64 */
      wishCount?: number
      wishNotice?: string
      /** Format: date-time */
      saleStartsAt?: string
      /** Format: date-time */
      saleEndsAt?: string
      shipping?: components['schemas']['DropShippingResponse']
      optionGroups?: components['schemas']['DropOptionGroupResponse'][]
      options?: components['schemas']['Option'][]
      actions?: components['schemas']['Actions']
      /** Format: date-time */
      serverTime?: string
    }
    ApiResponsePublicDropStockResponse: {
      success?: boolean
      data?: components['schemas']['PublicDropStockResponse']
      message?: string
    }
    PublicDropStockResponse: {
      /** Format: int64 */
      dropId?: number
      options?: components['schemas']['Option'][]
      /** Format: date-time */
      serverTime?: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  issuePresignedUrl: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ImageUploadUrlRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseImageUploadUrlResponse']
        }
      }
    }
  }
  listDrops: {
    parameters: {
      query?: {
        status?: 'DRAFT' | 'WISH' | 'GRAB' | 'ENDED' | 'CANCELED'
        page?: number
        size?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponsePageResponseSellerDropListResponse']
        }
      }
    }
  }
  createDraft: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['DropDraftRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseDropDraftResponse']
        }
      }
    }
  }
  publish: {
    parameters: {
      query?: never
      header?: never
      path: {
        dropId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseDropPublishResponse']
        }
      }
    }
  }
  cancel: {
    parameters: {
      query?: never
      header?: never
      path: {
        dropId: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['DropCancelRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseDropCancelResponse']
        }
      }
    }
  }
  findDrop: {
    parameters: {
      query?: never
      header?: never
      path: {
        dropId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseSellerDropDetailResponse']
        }
      }
    }
  }
  updateDraft: {
    parameters: {
      query?: never
      header?: never
      path: {
        dropId: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['DropDraftRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseDropDraftResponse']
        }
      }
    }
  }
  findWishCount: {
    parameters: {
      query?: never
      header?: never
      path: {
        dropId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseSellerDropWishCountResponse']
        }
      }
    }
  }
  findStocks: {
    parameters: {
      query?: never
      header?: never
      path: {
        dropId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseSellerDropStockResponse']
        }
      }
    }
  }
  listDrops_1: {
    parameters: {
      query?: {
        status?: 'DRAFT' | 'WISH' | 'GRAB' | 'ENDED' | 'CANCELED'
        categoryId?: number
        keyword?: string
        soldOut?: boolean
        sort?: string
        page?: number
        size?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponsePageResponsePublicDropListResponse']
        }
      }
    }
  }
  getDrop: {
    parameters: {
      query?: never
      header?: never
      path: {
        dropId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponsePublicDropDetailResponse']
        }
      }
    }
  }
  getStocks: {
    parameters: {
      query?: never
      header?: never
      path: {
        dropId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponsePublicDropStockResponse']
        }
      }
    }
  }
}
