/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/seller/orders/{orderId}/shipment': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['registerShipment']
    delete?: never
    options?: never
    head?: never
    patch: operations['updateShipment']
    trace?: never
  }
  '/api/v1/seller/orders/{orderId}/prepare-shipment': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['prepareShipment']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/orders': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['findMyOrders']
    put?: never
    post: operations['create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/seller/orders': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['listOrders']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/seller/orders/{orderId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['findOrder']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/orders/{orderId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['findMyOrder']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    ShipmentRegisterRequest: {
      carrier: string
      trackingNumber: string
    }
    ApiResponseOrderStatusResponse: {
      success?: boolean
      data?: components['schemas']['OrderStatusResponse']
      message?: string
    }
    OrderStatusResponse: {
      /** Format: uuid */
      orderId?: string
      status?: string
    }
    Item: {
      /** Format: int64 */
      optionId: number
      /** Format: int32 */
      quantity: number
    }
    OrderCreateRequest: {
      /** Format: int64 */
      dropId: number
      items: components['schemas']['Item'][]
      shippingAddress: components['schemas']['ShippingAddress']
    }
    ShippingAddress: {
      recipient: string
      phone: string
      postalCode: string
      address1: string
      address2?: string
      deliveryMemo?: string
    }
    ApiResponseOrderCreateResponse: {
      success?: boolean
      data?: components['schemas']['OrderCreateResponse']
      message?: string
    }
    OrderCreateResponse: {
      /** Format: uuid */
      orderId?: string
      orderNumber?: string
      /** @enum {string} */
      status?:
        | 'PAYMENT_PENDING'
        | 'PAID'
        | 'PREPARING'
        | 'SHIPPED'
        | 'DELIVERED'
        | 'EXPIRED'
        | 'CANCELED'
      items?: components['schemas']['Item'][]
      /** Format: int64 */
      itemsAmount?: number
      /** Format: int64 */
      shippingAmount?: number
      /** Format: int64 */
      totalAmount?: number
      /** Format: date-time */
      paymentExpiresAt?: string
    }
    ApiResponseShipmentUpdateResponse: {
      success?: boolean
      data?: components['schemas']['ShipmentUpdateResponse']
      message?: string
    }
    ShipmentUpdateResponse: {
      /** Format: uuid */
      orderId?: string
      status?: string
      carrier?: string
      trackingNumber?: string
    }
    ApiResponsePageResponseSellerOrderListResponse: {
      success?: boolean
      data?: components['schemas']['PageResponseSellerOrderListResponse']
      message?: string
    }
    PageResponseSellerOrderListResponse: {
      content?: components['schemas']['SellerOrderListResponse'][]
      /** Format: int32 */
      page?: number
      /** Format: int32 */
      size?: number
      /** Format: int64 */
      totalElements?: number
      /** Format: int32 */
      totalPages?: number
      hasNext?: boolean
    }
    SellerOrderListResponse: {
      /** Format: uuid */
      orderId?: string
      orderNumber?: string
      /** Format: int64 */
      dropId?: number
      productName?: string
      sellerName?: string
      orderStatus?: string
      paymentStatus?: string
      /** Format: int64 */
      itemsAmount?: number
      /** Format: int64 */
      shippingAmount?: number
      /** Format: int64 */
      totalAmount?: number
      /** Format: date-time */
      orderedAt?: string
    }
    ApiResponseSellerOrderDetailResponse: {
      success?: boolean
      data?: components['schemas']['SellerOrderDetailResponse']
      message?: string
    }
    OrderItemResponse: {
      productName?: string
      optionName?: string
      /** Format: int64 */
      unitPrice?: number
      /** Format: int32 */
      quantity?: number
      /** Format: int64 */
      subtotal?: number
    }
    OrderShippingResponse: {
      /** @enum {string} */
      status?:
        | 'PAYMENT_PENDING'
        | 'PAID'
        | 'PREPARING'
        | 'SHIPPED'
        | 'DELIVERED'
        | 'EXPIRED'
        | 'CANCELED'
      carrier?: string
      trackingNumber?: string
      /** Format: date-time */
      deliveredAt?: string
    }
    SellerOrderDetailResponse: {
      /** Format: uuid */
      orderId?: string
      orderNumber?: string
      /** @enum {string} */
      status?:
        | 'PAYMENT_PENDING'
        | 'PAID'
        | 'PREPARING'
        | 'SHIPPED'
        | 'DELIVERED'
        | 'EXPIRED'
        | 'CANCELED'
      items?: components['schemas']['OrderItemResponse'][]
      /** Format: int64 */
      itemsAmount?: number
      /** Format: int64 */
      shippingAmount?: number
      /** Format: int64 */
      totalAmount?: number
      /** @enum {string} */
      paymentStatus?:
        'PENDING' | 'SUCCEEDED' | 'FAILED' | 'UNKNOWN' | 'CANCELED'
      shipping?: components['schemas']['OrderShippingResponse']
      /** Format: date-time */
      orderedAt?: string
    }
    ApiResponsePageResponseMyOrderListResponse: {
      success?: boolean
      data?: components['schemas']['PageResponseMyOrderListResponse']
      message?: string
    }
    MyOrderListResponse: {
      /** Format: uuid */
      orderId?: string
      orderNumber?: string
      productName?: string
      /** @enum {string} */
      status?:
        | 'PAYMENT_PENDING'
        | 'PAID'
        | 'PREPARING'
        | 'SHIPPED'
        | 'DELIVERED'
        | 'EXPIRED'
        | 'CANCELED'
      /** Format: int64 */
      totalAmount?: number
      /** Format: date-time */
      orderedAt?: string
    }
    PageResponseMyOrderListResponse: {
      content?: components['schemas']['MyOrderListResponse'][]
      /** Format: int32 */
      page?: number
      /** Format: int32 */
      size?: number
      /** Format: int64 */
      totalElements?: number
      /** Format: int32 */
      totalPages?: number
      hasNext?: boolean
    }
    ApiResponseMyOrderDetailResponse: {
      success?: boolean
      data?: components['schemas']['MyOrderDetailResponse']
      message?: string
    }
    MyOrderDetailResponse: {
      /** Format: uuid */
      orderId?: string
      orderNumber?: string
      /** @enum {string} */
      status?:
        | 'PAYMENT_PENDING'
        | 'PAID'
        | 'PREPARING'
        | 'SHIPPED'
        | 'DELIVERED'
        | 'EXPIRED'
        | 'CANCELED'
      items?: components['schemas']['OrderItemResponse'][]
      /** Format: int64 */
      itemsAmount?: number
      /** Format: int64 */
      shippingAmount?: number
      /** Format: int64 */
      totalAmount?: number
      /** @enum {string} */
      paymentStatus?:
        'PENDING' | 'SUCCEEDED' | 'FAILED' | 'UNKNOWN' | 'CANCELED'
      /** Format: date-time */
      paymentExpiresAt?: string
      shipping?: components['schemas']['OrderShippingResponse']
      /** Format: date-time */
      orderedAt?: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  registerShipment: {
    parameters: {
      query?: never
      header?: {
        'Idempotency-Key'?: string
      }
      path: {
        orderId: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ShipmentRegisterRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseOrderStatusResponse']
        }
      }
    }
  }
  updateShipment: {
    parameters: {
      query?: never
      header?: never
      path: {
        orderId: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ShipmentRegisterRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseShipmentUpdateResponse']
        }
      }
    }
  }
  prepareShipment: {
    parameters: {
      query?: never
      header?: never
      path: {
        orderId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseOrderStatusResponse']
        }
      }
    }
  }
  findMyOrders: {
    parameters: {
      query?: {
        status?:
          | 'PAYMENT_PENDING'
          | 'PAID'
          | 'PREPARING'
          | 'SHIPPED'
          | 'DELIVERED'
          | 'EXPIRED'
          | 'CANCELED'
        page?: number
        size?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponsePageResponseMyOrderListResponse']
        }
      }
    }
  }
  create: {
    parameters: {
      query?: never
      header?: {
        'Idempotency-Key'?: string
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['OrderCreateRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseOrderCreateResponse']
        }
      }
    }
  }
  listOrders: {
    parameters: {
      query?: {
        dropId?: number
        orderStatus?:
          | 'PAYMENT_PENDING'
          | 'PAID'
          | 'PREPARING'
          | 'SHIPPED'
          | 'DELIVERED'
          | 'EXPIRED'
          | 'CANCELED'
        paymentStatus?:
          'PENDING' | 'SUCCEEDED' | 'FAILED' | 'UNKNOWN' | 'CANCELED'
        page?: number
        size?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponsePageResponseSellerOrderListResponse']
        }
      }
    }
  }
  findOrder: {
    parameters: {
      query?: never
      header?: never
      path: {
        orderId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseSellerOrderDetailResponse']
        }
      }
    }
  }
  findMyOrder: {
    parameters: {
      query?: never
      header?: never
      path: {
        orderId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseMyOrderDetailResponse']
        }
      }
    }
  }
}
