/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/orders/{orderId}/payments': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['pay']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/orders/{orderId}/cancel': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['cancel']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    PaymentRequest: {
      paymentKey: string
      /** Format: int64 */
      amount: number
    }
    ApiResponsePaymentResponse: {
      success?: boolean
      data?: components['schemas']['PaymentResponse']
      message?: string
    }
    Failure: {
      code?: string
      message?: string
    }
    PaymentResponse: {
      /** Format: uuid */
      paymentId?: string
      /** Format: uuid */
      orderId?: string
      orderNumber?: string
      /** Format: int64 */
      amount?: number
      /** @enum {string} */
      status?: 'PENDING' | 'SUCCEEDED' | 'FAILED' | 'UNKNOWN' | 'CANCELED'
      /** @enum {string} */
      reconciliationStatus?: 'NONE' | 'REQUIRED' | 'RESOLVED'
      /** Format: date-time */
      paidAt?: string
      failure?: components['schemas']['Failure']
    }
    OrderCancelRequest: {
      reason: string
    }
    ApiResponseOrderCancelResponse: {
      success?: boolean
      data?: components['schemas']['OrderCancelResponse']
      message?: string
    }
    OrderCancelResponse: {
      /** Format: uuid */
      orderId?: string
      /** @enum {string} */
      status?:
        | 'PAYMENT_PENDING'
        | 'PAID'
        | 'PREPARING'
        | 'SHIPPED'
        | 'DELIVERED'
        | 'EXPIRED'
        | 'CANCELED'
      /** @enum {string} */
      refundStatus?: 'NONE' | 'SUCCEEDED' | 'UNKNOWN'
      /** Format: date-time */
      canceledAt?: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  pay: {
    parameters: {
      query?: never
      header?: {
        'Idempotency-Key'?: string
      }
      path: {
        orderId: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PaymentRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponsePaymentResponse']
        }
      }
    }
  }
  cancel: {
    parameters: {
      query?: never
      header?: {
        'Idempotency-Key'?: string
      }
      path: {
        orderId: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['OrderCancelRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseOrderCancelResponse']
        }
      }
    }
  }
}
