/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/auth/email-verification': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * 이메일 인증 코드 요청
     * @description 가입 여부와 관계없이 같은 응답이며, 메일 발송 완료를 기다리지 않는다. 발송 제한은 MEMBER_AUTH.md 1.2 참고
     */
    post: operations['requestCode']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/email-verification/confirm': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * 이메일 인증 코드 확인
     * @description 성공하면 15분간 유효한 가입 토큰을 email_signup_token HttpOnly 쿠키로 발급한다. 코드 형식 오류는 시도 횟수에 포함하지 않는다
     */
    post: operations['confirmCode']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    EmailVerificationRequest: {
      email: string
    }
    EmailVerificationConfirmRequest: {
      email: string
      code: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  requestCode: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['EmailVerificationRequest']
      }
    }
    responses: {
      /** @description 요청 처리 완료 */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description INVALID_REQUEST, VALIDATION_FAILED, INVALID_EMAIL */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description EMAIL_VERIFICATION_RESEND_TOO_SOON */
      429: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  confirmCode: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['EmailVerificationConfirmRequest']
      }
    }
    responses: {
      /** @description 확인 성공, Set-Cookie로 가입 토큰 발급 */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description INVALID_REQUEST, VALIDATION_FAILED, INVALID_EMAIL, EMAIL_VERIFICATION_CODE_MISMATCH, EMAIL_VERIFICATION_CODE_EXPIRED */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description DUPLICATE_EMAIL */
      409: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description EMAIL_VERIFICATION_ATTEMPTS_EXCEEDED */
      429: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
}
