/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/drops/{dropId}/wish': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: operations['register']
    post?: never
    delete: operations['cancel']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/users/me/wishes': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['listMyWishes']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    ApiResponseWishResponse: {
      success?: boolean
      data?: components['schemas']['WishResponse']
      message?: string
    }
    WishResponse: {
      /** Format: int64 */
      dropId?: number
      wished?: boolean
      /** Format: date-time */
      wishedAt?: string
      notice?: string
    }
    ApiResponsePageResponseWishListResponse: {
      success?: boolean
      data?: components['schemas']['PageResponseWishListResponse']
      message?: string
    }
    PageResponseWishListResponse: {
      content?: components['schemas']['WishListResponse'][]
      /** Format: int32 */
      page?: number
      /** Format: int32 */
      size?: number
      /** Format: int64 */
      totalElements?: number
      /** Format: int32 */
      totalPages?: number
      hasNext?: boolean
    }
    WishListResponse: {
      /** Format: int64 */
      dropId?: number
      name?: string
      thumbnailUrl?: string
      /** Format: int64 */
      minPrice?: number
      /** @enum {string} */
      status?: 'DRAFT' | 'WISH' | 'GRAB' | 'ENDED' | 'CANCELED'
      /** Format: date-time */
      wishedAt?: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  register: {
    parameters: {
      query?: never
      header?: never
      path: {
        dropId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseWishResponse']
        }
      }
    }
  }
  cancel: {
    parameters: {
      query?: never
      header?: never
      path: {
        dropId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  listMyWishes: {
    parameters: {
      query?: {
        page?: number
        size?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponsePageResponseWishListResponse']
        }
      }
    }
  }
}
